### ISSUE TITLE
Get weird results

### ISSUE THREAD

**Issue by Ecalpal** [MMOCKING/RadarCam-Depth#1]
![1686210161650926080](https://github.com/MMOCKING/RadarCam-Depth/assets/39435901/0f2948a1-1e58-44f5-8890-dacf04c495df)
result/rcnet/depth_predicted_colors/1686210161650926080.png

rcnet_run_zju.py

restore_path = './weights/rcnet/model-128000.pth',
patch_size = [300, 100],
normalized_image_range = [0, 1],

encoder_type = ['rcnet', 'batch_norm'],
n_filters_encoder_image = [32, 64, 128, 128, 128],
n_neurons_encoder_depth = [32, 64, 128, 128, 128],
decoder_type = ['multiscale', 'batch_norm'],
n_filters_decoder = [256, 128, 64, 32, 16],
weight_initializer = 'kaiming_uniform',
activation_func = 'leaky_relu',
response_thr = 0.5

Can you check the checkpoint?

**Comment by MMOCKING** [comment]
This is the intermediate output (quasi-dense depth) generated by the RC-Net module. If you need to generate the final dense depth, use sml_run_zju.py.
