### ISSUE TITLE
About initial depth (Monocular depth estimation)

### ISSUE THREAD

**Issue by RaymondWang987** [MMOCKING/RadarCam-Depth#13]
Dear authors,

Thanks for sharing the great work. I have one questions regarding the initial relative depth from MiDaS and DPT.

MiDaS and DPT produce relative disparity (i.e., relative inverse depth), which has no constrain on the value range and can be negative or zero. During training and inference, what format (depth or disparity) is used as the input of your model? 

If you adopt depth maps, how do you conduct the transformation? Directly converting the MiDaS disparity to relative depth by z=1/d is inapplicable due to the unconstrained value range.

**Comment by MMOCKING** [comment]
Thank you for your interest in our work and for raising this important question.

To address your inquiry, our approach involves using global alignment with radar depth to initially align the scale-less depth estimates. This step helps mitigate the issues associated with the unconstrained value range of the relative disparity produced by MiDaS and DPT.

Additionally, during the preprocessing stage before inputting the depth maps into the network, we handle the potential problems of zero or negative values by truncating these values. This ensures that the depth input to the model is well-conditioned and avoids the challenges you've mentioned.
