### ISSUE TITLE
Train on Nuscenes dataset

### ISSUE THREAD

**Issue by lotterf** [MMOCKING/RadarCam-Depth#8]
Hello, I want to train the model on the Nuscenes dataset, how do I get the depth truth value to supervise the training? If I use LiDAR to generate images with sparse depth, will it result in poor results?I would appreciate it if you could answer my questions.

**Comment by MMOCKING** [comment]
Preprocessing and dataloader of the nuScenes dataset can be found at [radar-camera-fusion-depth](https://github.com/nesl/radar-camera-fusion-depth). Accumulated and interpolated lidar depth are used to generate gt for nuScenes. As mentioned, the sparse LiDAR point clouds in the nuScenes dataset result in poor performance, making it potentially unsuitable for supervised dense depth estimation.
