### ISSUE TITLE
Download the ZJU-4DRadarCam dataset

### ISSUE THREAD

**Issue by lotterf** [MMOCKING/RadarCam-Depth#9]
Hello, I would like to ask if there are other ways to download the ZJU-4DRadarCam dataset, which I cannot download on onedrive.thanks.

**Comment by Lurvelly** [comment]
I also would like to know other way to download the dataset, is there any download address for Baidu Netdisk?

**Comment by MMOCKING** [comment]
Sorry for my delay~
